### ISSUE TITLE
"Rheinbrücke Maxau" missing in graph data

### ISSUE THREAD

**Issue by Tarirah** [RoutingKit/RoutingKit#64] opened 2018-10-01 23:24 UTC
I use RoutingKit to convert OSM data to a graph,
using the `simple_load_osm_car_routing_graph_from_pbf()`-method.
I also enable the `all_modelling_nodes_are_routing_nodes` flag.
I then dump the vectors to the hard drive (and load them again as shown in check) as shown by the file I attached (not completely minimal as it contains some additional tests).

I have also attached two Images, the first showing the graph data as exported by RoutingKit, rendered over the Data queried directly from OpenStreetMap,  (which does not contain the bridge), as well as an image showing routing in openstreetmap.org (https://www.openstreetmap.org/directions?engine=osrm_car&route=49.01510%2C8.34730%3B49.04048%2C8.28846#map=14/49.0276/8.3193&layers=N).
As one can see, the second image does contain the bridge whereas the first one does not.

As for the data I convert, I used an export of the europe graph from geofabric downloaded today, with

    sha256sum europe-latest.osm.pbf
    86acbdeed5e65095fddb2e618989c2ca25cd8bb1fa181afe7597464bec02ec49 europe-latest.osm.pbf

but the same problem exists with a much older export (from 2018/05/20).

Graph display (red lines are edges in the exported graph) 
![image](https://user-images.githubusercontent.com/21111390/46320681-cb0ff680-c5df-11e8-9cd7-433db4fe7294.png)

Actual route that uses the bridge:
![image](https://user-images.githubusercontent.com/21111390/46320702-e418a780-c5df-11e8-9976-8f3966cf1a7f.png)

Converter Script (written in C++17), compiled with:
`g++ -IRoutingKit/include -std=c++17 -lgtest -Wall -Wextra -g -O3 -march=native -ffast-math  -LRoutingKit/lib -lroutingkit -lstdc++fs -lpthread    hardcode.o -o hardcode -LRoutingKit/lib -lroutingkit -lstdc++fs -lpthread`
[hardcode.txt](https://github.com/RoutingKit/RoutingKit/files/2435981/hardcode.txt)

**Comment by ben-strasser** [comment] 2018-10-02 06:18
The problem is that the road of the bridge has "motorroad=no" ( 
https://www.openstreetmap.org/way/5043513 ) and that the code in 
osm_profile.cpp interprets this as motor vehicles not being allowed on 
the road. From ( https://wiki.openstreetmap.org/wiki/Key:motorroad ) it 
is unclear to me what "motorroad=no" is even supposed to mean. One can 
argue that this is a mapping bug. One can argue that RoutingKit should 
disregard the value of this tag.

**Comment by boldtrn** [comment] 2018-10-09 12:00
> it is unclear to me what "motorroad=no" is even supposed to mean

IMHO this means that it's not a "[Kraftfahrtsstraße](https://de.wikipedia.org/wiki/Kraftfahrstra%C3%9Fe)". This makes sense in the combination with highway=trunk and most probably is not a mapping bug.

**Comment by Tarirah** [comment] 2018-10-09 15:59
From my limited understanding of OSM mapping, it seems to me that motorroad=true is to mean that no bikes and pedestrians can go there, but in the case of the bridge it actually has walkways on the side, where those can go. I have created  a pull request #65 that removes the check.

**Comment by ben-strasser** [comment] 2018-10-14 07:27
Thanks for the patch. Pull request merged. The motorroad tag no longer affects whether cars can take a road or not.

**Closed by ben-strasser** 2018-10-14 07:27 UTC
